version: "3.7"
x-project-repository-mount:
  &project-repository-mount
  type: bind
  source: $REPOSITORY_PATH
  
x-project-mount:
  &project-database-mount
  type: bind
  source: $DATABASE_PATH

x-project-base:
  &project-base
  env_file:
    - .env
  restart: always

x-env-file-mount:
  &env-file-mount
  type: bind
  source: .env

networks:
  default:
    external:
      name: "source-verify-${TAG}"
  
services:
  s3sync:
    <<: *project-base
    image: ethereum/source-verify:s3-${TAG}
    container_name: s3-${TAG}
    volumes:
      - <<: *env-file-mount
        target: /app/.env
      - <<: *project-repository-mount
        target: /app/repository/repository/
      - <<: *project-database-mount
        target: /app/repository/database/
